services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: servidores-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - db
      - minio
    networks:
      - servidores-network

  webserver:
    image: nginx:alpine
    container_name: servidores-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - servidores-network

  db:
    image: postgres:15
    container_name: servidores-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - servidores-network

  minio:
    image: minio/minio
    container_name: servidores-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
      - ./docker/minio/initialize.sh:/docker-entrypoint-init.d/initialize.sh
    networks:
      - servidores-network

volumes:
  postgres_data:
  minio_data:

networks:
  servidores-network:
    driver: bridge